version: "3.7"

networks:
  app_network:
    driver: bridge

volumes:
  postgres_db:
  js_data:
  event_store_data:
  event_store_logs:

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    networks:
      - app_network
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "secret"

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=db@app.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "4053:80"
    restart: always
    networks:
      - app_network

  eventstore:
    image: eventstore/eventstore:22.10.2-buster-slim
    container_name: eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: event_store_data
        target: /var/lib/eventstore
      - type: volume
        source: event_store_logs
        target: /var/log/eventstore
    networks:
      - app_network

  nats:
    image: nats:2.9-alpine
    container_name: nats
    hostname: nats
    ports:
      - "4222:4222"
    command:
      - -js
      - -sd
      - /var/lib/nats/data
    volumes:
      - js_data:/var/lib/nats/data